output_dir: data/indonesian
queries:
  - Bus Indonesia
  - SUV Car Indonesia
  - MPV Car Indonesia
images_per_query: 5
min_width: 640
min_height: 480
sources:
  google: false
  bing: true
  duckduckgo: true
scraping_settings:
  headless: true
  delay_between_downloads:
    - 0.5
    - 1.5
  delay_between_scrolls:
    - 1.0
    - 2.0
  max_scrolls: 2
  timeout: 30
